### ISSUE TITLE
Can't connect to vCenter Server using Magpie appliance

### ISSUE THREAD

**Issue by timtyn123** [vmware/powernsx#521] opened 2018-05-29 16:23 UTC
Trying to connect using "Connect-NsxServer -vCenterServer x.x.x.x.  The command works on a Windows based PowerNSX VM we have running.  And I can connect to the NSX Manager when I use -NsxServer, but then throws a similar error when I try to connect to the vCenter.   I get the following error:
Unable to determine NSX server endpoint from vCenter. 05/29/2018 16:18:45       Connect-VIServer                The request channel timed out attempting to send after 00:05:00. Increase the timeout value passed to the call to Request or increase the SendTim
eout value on the B
inding. The time allotted to this operation may have been a portion of a longer timeout.
At /usr/local/share/powershell/Modules/PowerNSX/PowerNSX.psm1:4857 char:13
+             throw "Unable to determine NSX server endpoint from vCent ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to deter...onger timeout.       :String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to determine NSX server endpoint from vCenter. 05/29/2018 16:18:45 Connect-VIServer                The request channel timed out attempting to send after 00:05:00. Increase the timeout value passed to the call to Request
 or increase
    the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

**Comment by nmbradford** [comment] 2018-05-29 22:09
Thanks @timtyn123 - can you do a straight connect-viserver xxx with the same vcenter server?  If not (and the server is reachable) then the issue is probably with PowerCLI Core itself.  We are actually about to release an updated Magpie with GA versions of PoSH Core and PowerCLI 10 so it may be worth waiting to test with that?  Ill update this issue when its available so you know.  If connect-viserver does work let me know and we can dig a bit more.

**Comment by timtyn123** [comment] 2018-05-30 00:48
Nick
The connect-viserver command in PowerCLI doesn't work either.  We working fine with the Windows PowerNSX/PowerCLI for now.  I'll keep an eye out for when the new version comes out and give it try.  Thanks.

**Comment by nmbradford** [comment] 2018-08-16 03:06
FYI Magpie v0.2 was released in June.  https://github.com/nmbradford/magpie-release.  Ill close this for now, please comment back if you continue to have issues.

**Closed by nmbradford** 2018-08-16 03:06 UTC
