### ISSUE TITLE
Accept SSO/AD username for NSX credentials

### ISSUE THREAD

**Issue by neilcat** [vmware/powernsx#50] opened 2016-10-17 02:27 UTC
Currently Connect-NSXServer tests credentials with `$URI = "/api/1.0/appliance-management/global/info"` 

This API is not usable with a SSO or Active Directory and can only be called with a local NSX CLI user although a majority of the use cases for PowerNSX can be called with a non-local user.

Ideally need connect-nsxserver to allow non-local users and maybe display a warning that functionality might be limited but continue.

**Comment by pandom** [comment] 2016-10-17 09:13
Currently this is a known limitation of the API. There are currently product feature requests that have been made to bring the ability to use SSO on api/1.0 accounts. 

At this stage it is not known when or if these will be implemented.

In the mean time it is possible to create another connection with another user.

Creating an API user locally is possible with following Dale's steps here.

http://www.sneaku.com/2016/01/22/how-to-create-a-nsx-v-api-user-account/

Then you can create an alternate connection to NSX Manager. ($LOCALCONNECTION connect-nsxserver) and use the -connection $LOCALCONNECTION option with the newly defined local on all commands. This would allow you to work around this. 

Please let me know if this helps or not.

-Anthony

**Comment by nmbradford** [comment] 2016-10-18 04:54
Duplicate of https://github.com/vmware/powernsx/issues/5

**Closed** 2016-10-18 04:54 UTC
Labels: bug, duplicate
